name: Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'temurin'
          cache: maven
      - name: Run unit tests
        run: mvn test
      - name: Build with Maven
        run: mvn clean install
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: kreal321/github-action-test
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}